# Data frames needed come from model simulation codes in phyto_simulations.R
# Due to the large number of simulations, the data frames are not included in this repository,
# but can be generated by running the code in phyto_simulations.R

# Creating a common data frame for all simulation outputs
# to contain daily values of total abundance and descriptors of compositional change and nutrient fluxes
total_bm           <- as.data.frame(matrix(NA, ncol = 10, nrow = 365*300*4*9))
colnames(total_bm) <- c("day","nutrient_load","N","P","NP_ratio","temp_scen","Scenario","community","sp_number","abundance")
total_bm$day           <- 366:730
total_bm$nutrient_load <- rep(1:9, each = 365*300*4)
total_bm$N             <- rep(sources[,1], each = 365*300*4)
total_bm$P             <- rep(sources[,2], each = 365*300*4)
total_bm$NP_ratio      <- total_bm$N / total_bm$P
total_bm$temp_scen     <- rep(rep(c("temp_scen1","temp_scen2","temp_scen3","temp_scen4"), each = 365*300), times = 9)
total_bm$Scenario      <- rep(rep(c("Baseline","+1°C","+2°C","+3°C"), each = 365*300), times = 9)
total_bm$community     <- rep(1:300, each = 365)
total_bm$sp_number     <- rep(c(10,30,50), each = 365*100)
total_bm$num_scen      <- as.numeric(substr(total_bm$temp_scen, start = 10, stop = 10))
total_bm$unique_com    <- 1:nrow(total_bm)

# Extracting daily total abundance and inorganic nutrient values
total_bm$abundance <- NA
total_bm$N_inc <- NA
total_bm$P_inc <- NA
for(scen in 1:4) {
  for(lo in 1:9) {
    for(com in 1:300) {
      
      total_bm$abundance[total_bm$temp_scen == names(sim_phyto_random_9)[scen] &
                           total_bm$nutrient_load == lo &
                           total_bm$community == com] <-
        sim_phyto_random_9[[scen]][[lo]][[com]]$total.abund[366:730] # extracting year 2 only
      
      total_bm$N_inc[total_bm$temp_scen == names(sim_phyto_random_9)[scen] &
                       total_bm$nutrient_load == lo &
                       total_bm$community == com] <-
        sim_phyto_random_9[[scen]][[lo]][[com]]$N[366:730]
      
      total_bm$P_inc[total_bm$temp_scen == names(sim_phyto_random_9)[scen] &
                       total_bm$nutrient_load == lo &
                       total_bm$community == com] <-
        sim_phyto_random_9[[scen]][[lo]][[com]]$P[366:730]
      
    }
  }
}

